# Generated by Django 3.2.7 on 2021-09-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
